.github/workflows/lint-test.yaml
.github/workflows/release.yaml

Inspired by [this example repo](https://github.com/helm/chart-testing-action), this PR should implement GitHub Actions support which will:
* For every PR impacting the helm chart, a linter will make sure that the change passes linting which includes forcing a version bump on changes)
* For every PR impacting the helm chart, a 'kubernetes in docker' (KIND) cluster will be temporarily created and the chart will be installed to that test cluster to ensure that it installs properly
* For every merge to master impacting the helm chart, automation will package the chart, update the `index.yaml` on the `gh-pages` branch, and cut a github release with the packaged chart for reference as a chart repository.
**ACTION REQUIRED:**
* Github Pages should be enabled within the repo settings. Please use …

implement github actions for helm charts

---

README.md
charts/minecraft/.helmignore
charts/minecraft/Chart.yaml
charts/minecraft/OWNERS
charts/minecraft/README.md
charts/minecraft/ci/test-values.yaml
charts/minecraft/templates/NOTES.txt
charts/minecraft/templates/_helpers.tpl
charts/minecraft/templates/datadir-pvc.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/templates/minecraft-svc.yaml
charts/minecraft/templates/rcon-svc.yaml
charts/minecraft/templates/secrets.yaml
charts/minecraft/values.yaml

Importing 'minecraft' chart from helm/charts to this repo.
* Bumped chart version to 2.0.0 so that it will appear greater than the version on helm/charts (this will help when using `helm search`)
* Naming the chart `minecraft` to maintain compatibility with existing chart, but we can give it a different name if that makes more sense.

adding minecraft chart

---

charts/minecraft/Chart.yaml
charts/minecraft/ci/test-values.yaml

This change only affects CI tests and not actual user installations.

[minecraft] Fix EULA setting for CI tests

---

README.md
charts/minecraft-bedrock/Chart.yaml
charts/minecraft-bedrock/templates/deployment.yaml
charts/minecraft-bedrock/values.yaml

* Update repo README to show new chart
* add missing bedrock server options
* using default server values (for things like level name, world name, max players) sourced from [here](https://minecraft.gamepedia.com/Server.properties#Bedrock_Edition_3)

[minecraft-bedrock] adding additional bedrock server options

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/datadir-pvc.yaml

Using annotations for storageclass names was [deprecated in kubernetes
1.6](https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/#using-dynamic-provisioning) and causes issues with some backup/restore scenarios when still present.
This should still operate properly without the old-style annotation approach.

[minecraft] - Remove deprecated storageclass annotation

---

charts/minecraft-bedrock/Chart.yaml
charts/minecraft-bedrock/templates/datadir-pvc.yaml
charts/minecraft-bedrock/values.yaml

Using annotations for storageclass names was [deprecated in kubernetes
1.6](https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/#using-dynamic-provisioning) and causes issues with some backup/restore scenarios when still present.
This should still operate properly without the old-style annotation approach.
Also needed to bump the server version to '1.16.1.02' in order for it to download properly from upstream

[minecraft-bedrock] - Remove deprecated storageclass annotation

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/minecraft-svc.yaml
charts/minecraft/values.yaml

This change will allow users to specify an minecraftServer.externalIPs to allow access to the minecraft service instead of using a load balancer. 
Example:
```Bash
helm upgrade minecraft ./charts/minecraft -n default --set minecraftServer.eula=true --set minecraftServer.externalIPs='{192.168.1.25}'
```

Add externalIPs support for the minecraft service

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml

The previous capitalization caused `forcegameMode`'s value to be silently ignored

Fix capitalization of FORCE_GAMEMODE environment variable

---

charts/minecraft-bedrock/Chart.yaml
charts/minecraft-bedrock/templates/deployment.yaml
charts/minecraft-bedrock/values.yaml

Per conversation in issue https://github.com/itzg/docker-minecraft-bedrock-server/issues/103 This is the update to the chart to support the changes in the docker container for whitelisting users.
Requires https://github.com/itzg/docker-minecraft-bedrock-server/pull/105

Updating whitelist and adding whitelist users option

---

charts/minecraft-bedrock/Chart.yaml
charts/minecraft-bedrock/templates/minecraft-svc.yaml
charts/minecraft-bedrock/values.yaml
charts/minecraft/Chart.yaml
charts/minecraft/templates/minecraft-svc.yaml
charts/minecraft/values.yaml

This adds the ability to set the nodePort for the service that way we can get a predictable port when deploying this via nodeport. I added some documentation to the values files, but am not sure if this should be documented elsewhere

Add ability to specify node port for minecraft service

---

charts/minecraft/Chart.yaml
charts/minecraft/README.md

The default seems to be to disable the persistence — https://github.com/itzg/minecraft-server-charts/blob/d53bc8f12a548a6f7829137b7285b839c5848f22/charts/minecraft/values.yaml#L171

README reflecting current default

---

charts/minecraft-bedrock/Chart.yaml
charts/minecraft-bedrock/templates/deployment.yaml
charts/minecraft-bedrock/values.yaml
charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/values.yaml

With the advent of Docker's anonymous image pull limitations, some users have been implementing docker authenticated pulls in their kubernetes clusters.
In order to support an authenticated pull, kubernetes provides the `imagePullSecrets` directive to authenticate to either a private registry or authenticated to Docker Hub. This PR aims to allow users the flexibility on specifying their own image pull secret.
Please let me know how I can help assist in getting this merged!

adding imagePullSecrets support

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/values.yaml

Adding a startup probe to the chart.
I found that the initial downloads can take a long time. I had a startup world that was about 10 gigs of data, that took time to install as did paper. Adding this startup probe allowed the pod to complete the work before being killed and allows liveness checks to still be peppy to catch crashes.

Adding startup probe

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/templates/dynmap-ing.yaml
charts/minecraft/templates/dynmap-svc.yaml
charts/minecraft/values.yaml

Added dynmap support as discussed in #37. This is more tailored at dynmap and allows easily opening a port or adding an ingress for dynmap, but will not install the dynmap plugin for you.

adding dynmap support

---

charts/minecraft-bedrock/Chart.yaml
charts/minecraft-bedrock/templates/minecraft-svc.yaml
charts/minecraft-bedrock/values.yaml
charts/minecraft/Chart.yaml
charts/minecraft/templates/minecraft-svc.yaml
charts/minecraft/templates/rcon-svc.yaml
charts/minecraft/values.yaml

The java edition chart [seems to have the `serviceAnnotations` misplaced](https://github.com/itzg/minecraft-server-charts/blob/4256283a24302ac70d9edd8f7a80b6ea17ad9160/charts/minecraft/values.yaml#L160) compared to the pod and deployment annotations. So, in this PR I'm proposing that `serviceAnnotations` be a top level value.
Went ahead and made the same change for bedrock since it was lacking that value all together.
Fixes #41

Added serviceAnnotations to minecraft-svc manifests

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/minecraft-svc.yaml
charts/minecraft/templates/rcon-svc.yaml
charts/minecraft/values.yaml

In addition to introducing a specific `rconServiceAnnotations` I fixed the yaml indentation for the service annotations. They were all adding a redundant indentation on the first yaml entry.
I'm wondering if I should have used a template merge operator to combine the now-deprecated values into the new one.
Fixes #45 
Related to #43

Corrected rendering of rcon service annotations

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/templates/dynmap-ing.yaml
charts/minecraft/templates/dynmap-svc.yaml
charts/minecraft/values.yaml

Fixes #53 
BREAKING CHANGE: `dynmap` refs in values are replaced with `extraPort`

fix(minecraft)!: replace references to dynmap with extraPort

---

charts/minecraft-proxy/Chart.yaml
charts/minecraft-proxy/templates/configmap.yaml

This PR corrects an issue caused by a duplicate block scaler token in the ConfigMap created when the `minecraftProxy.config` value is supplied.
The current ConfigMap template defines the `config.yml` file as follows:
```
data:
config.yml: |
{{ toYaml .Values.minecraftProxy.config | indent 4 }}
```
Using the following `custom-values.yml` as an example:
```
minecraftProxy:
config: |
---
online_mode: true
servers:
lobby:
motd: 'Testing...'
address: minecraft-minecraft:25565
restricted: false
```
and after rendering the template, the resulting `config.yml` file is not valid yaml:
```
keith.king at jump in ~/.../charts/minecraft-proxy on (HEAD detached at minecraft-proxy-2.0.1)*
$ helm template -f values.yaml -f custom-values.yml bungeecord .
<truncated for brevity>
---
apiVersion: v1
kind: …
```

minecraft-proxy: Correct rendering with toYaml in ConfigMap

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/templates/secrets.yaml
charts/minecraft/values.yaml

Inspired by the [grafana chart](https://github.com/grafana/helm-charts/blob/main/charts/grafana).
The ability to use an existing secret for the rcon password allows users to add the `values.yaml` to version control without exposing the password.

Support usage of an existing secret for rcon

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/NOTES.txt
charts/minecraft/templates/minecraft-svc.yaml
charts/minecraft/values.yaml

Changing the external service port is useful when using the type `LoadBalancer` with `k3s` (maybe cloud clusters as well). 
Previously it was not possible to run multiple instances with type `LoadBalancer`, as the it does not expose the `nodePort`, but the `port` of a service.

Allow changing the service port

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/values.yaml

Simple PR to add support for the CURSEFORGE type via CF_SERVER_MOD.
In the interim, can work around this by using extraEnv to set CF_SERVER_MOD directly.

Add support for CURSEFORGE + CF_SERVER_MOD

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/templates/extraports-svc.yaml
charts/minecraft/values.yaml

We've got a service for voice chat in-game which requires UDP, I realized this option was not exposed, so here it is.

fix(minecraft): expose protocol config for extra ports

---

charts/minecraft-proxy/Chart.yaml
charts/minecraft-proxy/templates/deployment.yaml
charts/minecraft-proxy/templates/extraports-ing.yaml
charts/minecraft-proxy/templates/extraports-svc.yaml
charts/minecraft-proxy/values.yaml

Identical to the change to `minecraft`, to enable extra ports to be exposed to the proxy

feat(minecraft-proxy): add extra port capability

---

charts/minecraft-proxy/Chart.yaml
charts/minecraft-proxy/templates/extraports-svc.yaml
charts/minecraft-proxy/templates/proxy-svc.yaml
charts/minecraft-proxy/values.yaml

This allows you to embed the service port in the proxy service in the event you would like your extra ports to share the same service.
This is useful for sharing a single load balancer IP with MetalLB & still being able to use the Local external traffic policy to retain the origin IPs.

feat(minecraft-proxy): add embedded service option to extraports

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/extraports-svc.yaml
charts/minecraft/templates/minecraft-svc.yaml
charts/minecraft/values.yaml

As per #78, but for the `minecraft` chart

feat(minecraft): add embedded service option to extraports

---

charts/minecraft-proxy/Chart.yaml
charts/minecraft/Chart.yaml
charts/minecraft/templates/_helpers.tpl

Fixes issue introduced with #60.  It looks like `.Capabilities.KubeVersion.GitVersion` [has been deprecated](https://github.com/helm/helm/blob/2f4ef705a9e8ea0e38a2c99c29c5e4de59b03d75/pkg/chartutil/capabilities.go#L60) and we should use  `.Capabilities.KubeVersion.Version` instead.

Fix kubeversion check in helper template

---

charts/minecraft-bedrock/Chart.yaml
charts/minecraft-bedrock/templates/deployment.yaml
charts/minecraft-bedrock/values.yaml
charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/values.yaml

- Add optional `envFrom` to deployments
- Update `extraEnv` to allow for setting `valueFrom` in env var specs
Fixes #71

Include `envFrom` and `env.value.valueFrom` in deployments

---

charts/minecraft-proxy/Chart.yaml
charts/minecraft-proxy/templates/extraports-ing.yaml
charts/minecraft-proxy/values.yaml
charts/minecraft/Chart.yaml
charts/minecraft/templates/extraports-ing.yaml
charts/minecraft/values.yaml

Add the field `ingressClassName` into the Ingress oject generated from the Chart templates. This is to support the use of IngressClass objects that replace the use of annotations (https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class) when specifying the Ingress Controller to use.
The behavior can be tested using the helm chart from (https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx) `v4.0.6` with this example `values.yaml`:
```yaml
controller:
watchIngressWithoutClass: false
ingressClassByName: true
electionID: ingress-controller-custom
ingressClassResource:
name: custom-nginx
enabled: true
default: false
controllerValue: "k8s.io/custom-ingress-nginx"
service:
externalIPs: 
- *your_ip*
replicaCount: 1
```

Add ingressClassName to templates

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/NOTES.txt

The echo command returned the wrong port (22565 instead of 25565)

Fixed small typo in local port forwarding

---

charts/minecraft-proxy/Chart.yaml
charts/minecraft-proxy/templates/extraports-svc.yaml
charts/minecraft-proxy/templates/proxy-svc.yaml
charts/minecraft-proxy/values.yaml
charts/minecraft/Chart.yaml
charts/minecraft/templates/extraports-svc.yaml
charts/minecraft/templates/minecraft-svc.yaml
charts/minecraft/values.yaml

I noticed that unlike other instances in the charts to expose services, you cannot specify a specific `nodePort`, if required, on the `extraPorts` service collection.  I had to edit the svc in kubernetes to specify this directly.  This PR will allow you to specify that in the `values.yaml` and avoid that direct edit in the kubernetes manifests to be overridden.

add nodePort option for extraPorts

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/values.yaml

Companion PR to itzg/docker-mc-backup#63. Add an `rcloneDestDir` param to the chart, mapped to the `RCLONE_DEST_DIR` environment variable for `mc-backup`.
Fixes #104.

Add rcloneDestDir param

---

charts/minecraft-bedrock/Chart.yaml
charts/minecraft-bedrock/templates/deployment.yaml
charts/minecraft-proxy/Chart.yaml
charts/minecraft-proxy/templates/deployment.yaml
charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml

It could be useful to create volumes without actually mounting them in
case if they are used exclusively for init containers

fix: Check if extraVolumes.volumeMounts is defined

---

charts/minecraft-bedrock/Chart.yaml
charts/minecraft-bedrock/templates/deployment.yaml
charts/minecraft-bedrock/values.yaml
charts/minecraft-proxy/Chart.yaml
charts/minecraft-proxy/templates/deployment.yaml
charts/minecraft-proxy/values.yaml
charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/values.yaml
charts/rcon-web-admin/Chart.yaml
charts/rcon-web-admin/templates/deployment.yaml

This PR updates the charts to utilize the current standard format for the image definition:
```yaml
image:
repository:
tag:
pullPolicy:
```
It should be non-breaking for those using the default `values.yaml` for the image portion of the chart.
What this does allow for, since it's the Helm standard format, is automation that is build around this standard for helm charts can be utilized.

Update charts to standard image.repo and image.tag

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml

Fixed a bug where `RESOURCE_PACK`, `RESOURCE_PACK_SHA1`, and `RESOURCE_PACK_ENFORCE` would not be set unless the user specified `vanillaTweaksShareCodes`.

BUGFIX: Resource Pack support on minecraft-server chart

---

charts/minecraft-bedrock/Chart.yaml
charts/minecraft-bedrock/templates/deployment.yaml
charts/minecraft-bedrock/values.yaml

Based on https://github.com/itzg/minecraft-server-charts/issues/141 I am pushing this feature.

Missing values in helm templates #141

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/values.yaml

Similar to #87 and #71, this PR adds the ability to specify `extraEnv` and `valueFrom` for the backup sidecar.
This makes the interface consistent with the primary container.

Include envFrom and valueFrom in mcbackup deployment

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/_helpers.tpl
charts/minecraft/templates/deployment.yaml

This solves these things:
- simplifies the ugly, repetitive two lines of env name-values
- provides a common mechanism to allow for null'ing out a value, such as `--set minecraftServer.maxWorldSize=`, leaving out the env var, and allowing `server.properties` value to be used instead.
- gets rid of inconsistent/redundant use of `default ""` clauses
@billimek , if this looks good to you, then I'll do the same for the other three charts.
For #143

feat(minecraft): allow values to fall back to server.properties default

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml

Without this fix, installing an FTBA pack results in;
```
Helm install failed: template: minecraft/templates/deployment.yaml:189:54: executing "minecraft/templates/deployment.yaml" at <required>: wrong number of args for required: want 2 got 0
```

Fix the use of required call for FTBA packs

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/rclone-secret.yaml

[This line](https://github.com/itzg/minecraft-server-charts/blob/396272c804d39fb7ccf09be042ceadeed6e3b177/charts/minecraft/templates/rclone-secret.yaml#L16), `{{ tpl .Values.mcbackup.rcloneConfig . | indent 4 | b64enc | quote }}` looks like it has the order of operations wrong.
With values such as,
```
minecraftServer:
rcon:
enabled: true
mcbackup:
enabled: true
backupInterval: '48h'
backupMethod: rclone
rcloneConfig: |
[remote]
type = s3
provider = Minio
env_auth = false
```
The template gives invalid yaml `Error: YAML parse error on minecraft/templates/rclone-secret.yaml: error converting YAML to JSON: yaml: line 14: could not find expected ':'`
```
apiVersion: v1
kind: Secret
metadata:
name: release-name-minecraft-rclone-config
labels:
app: release-name-minecraft
chart: …
```

Fix rclone secret indent level

---

charts/minecraft-bedrock/Chart.yaml
charts/minecraft-bedrock/templates/deployment.yaml
charts/minecraft-bedrock/values.yaml
charts/minecraft-proxy/Chart.yaml
charts/minecraft-proxy/templates/deployment.yaml
charts/minecraft-proxy/values.yaml
charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/values.yaml
charts/rcon-web-admin/Chart.yaml
charts/rcon-web-admin/templates/deployment.yaml
charts/rcon-web-admin/values.yaml

Use a strict security context by default to comply with the restricted pod security policy.
Fixes #154

use strict security context

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/_helpers.tpl
charts/minecraft/templates/deployment.yaml
charts/minecraft/values.schema.json
charts/minecraft/values.yaml

Also:
- introduces `minecraftServer.rcon.withGeneratedPassword` to support https://github.com/itzg/docker-minecraft-server/pull/2186
Resolves #153

minecraft: allow for boolean values to be defaulted

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/values.yaml

It might be useful when a user wants to install plugins using `initContainers`, but those plugins require running some commands in order to be configured.
For example, I'm installing plugins in an `emptyDir` volume, so they are reinstalled on each pod restart. But since configs are stored in the same dir, I can't just edit them there, because they exist on that `emptyDir` volume as well. So the idea of this PR is to let users do something like:
```YAML
spec:
containers:
name: minecraft-minecraft
lifecycle:
postStart:
exec:
command:
- bash
- -c
- for i in {1..100}; do mc-health && break || sleep 20; done && mc-send-to-console
say hello world
```

feat: Add container lifecycle to the main Minecraft container

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/backupdir-pvc.yaml
charts/minecraft/templates/datadir-pvc.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/templates/extraports-ing.yaml
charts/minecraft/templates/extraports-svc.yaml
charts/minecraft/templates/minecraft-svc.yaml
charts/minecraft/templates/rclone-secret.yaml
charts/minecraft/templates/rcon-svc.yaml
charts/minecraft/templates/secrets.yaml

I wanted to write a ServiceMonitor that would collect metrics from all k8s services with matching labels, and I found out that there are no common labels, so I could select all instances of this chart. Added some of recommended labels: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

Added labels recomended in k8s docs

---

.github/workflows/lint-test.yaml
charts/minecraft-bedrock/Chart.yaml
charts/minecraft-bedrock/templates/_helpers.tpl
charts/minecraft-bedrock/templates/extra-list.yaml
charts/minecraft-bedrock/values.yaml
charts/minecraft/Chart.yaml
charts/minecraft/templates/_helpers.tpl
charts/minecraft/templates/extra-list.yaml
charts/minecraft/values.yaml

Adds extraDeploy array which allows us to include additional objects at deployment. My reason for this is to use helm pre-install/post-delete hooks which can automatically add/remove DNS entries for my minecraft servers.
[Reference](https://helm.sh/docs/topics/charts_hooks/#the-available-hooks)

Added extraDeploy array

---

charts/minecraft-bedrock/Chart.yaml
charts/minecraft-bedrock/templates/deployment.yaml
charts/minecraft-bedrock/templates/minecraft-svc.yaml
charts/minecraft-bedrock/values.yaml

The ping function doesn't work if the server is accessed on an external port (eg nodePort) that isn't 19132. This change allows the port of the pod to match the external port.

Added minecraftServer.serverPort value to allow the pod to run on a different port for Bedrock

---

charts/minecraft/Chart.yaml
charts/minecraft/OWNERS
charts/minecraft/README.md
charts/minecraft/templates/_helpers.tpl
charts/minecraft/templates/deployment.yaml
charts/minecraft/templates/rclone-secret.yaml
charts/minecraft/values.schema.json
charts/minecraft/values.yaml

Also:
* Fixes a typo in the values' comments
* Adds documentation about a known immutable rclone configuration issue
* Add support for Restic environment variables to be read from Kubernetes resources

Add support for mc-backup using restic with rclone

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/values.schema.json
charts/minecraft/values.yaml

This is my WAG at adding mc-backup `rsync` support to the chart. It looks right. This is my first change to a helm chart. I'll have a few others to the proxy and perhaps support non-pvc based mounts for backup. I'm currently bypassing the chart and patching the yaml output before applying it. Would be nice to add the features to the chart and make life easier :)

Attemp to add mc-backup rsync method to helm

---

charts/minecraft-proxy/Chart.yaml
charts/minecraft-proxy/templates/proxy-svc.yaml
charts/minecraft-proxy/templates/rcon-svc.yaml
charts/minecraft-proxy/values.yaml

I'm running DualStack and need to expose the `ipFamilyPolicy` so I can get this to work. 
```yaml
ipFamilyPolicy: SingleStack
```

Expose ipFamilyPolicy

---

.github/workflows/lint-test.yaml
charts/minecraft/Chart.yaml
charts/minecraft/templates/backupdir-pvc.yaml
charts/minecraft/templates/datadir-pvc.yaml
charts/minecraft/values.yaml

Enables the user to alter the access mode to define Jobs in the extraDeployment array that can mount and modify the contents of the data directory.

Add ability to change access modes

---

charts/minecraft-proxy/Chart.yaml
charts/minecraft-proxy/templates/deployment.yaml
charts/minecraft-proxy/templates/secret.yaml
charts/minecraft-proxy/values.yaml

TLDR: Get secret out of values.yaml into existing secret that can be out of git tree. Stole from Minecraft chart. 
I am redeploying my k3s cluster for the kids Minecraft using fluxcd so it will be quicker in the future. I found where I couldn't, that I know of, easily get the rcon secret out of the chart. I saw how it was done in the Minecraft chart and stole that and implemented it here.

Allow using existing secret for proxy rcon

---

charts/mc-router/Chart.yaml
charts/mc-router/templates/api-service.yaml
charts/mc-router/templates/router-service.yaml
charts/mc-router/values.yaml

Allow setting annotations for the Service resources created by the `mc-router` chart in an independent fashion.
This is particularly useful when using services like MetalLB and setting either service type to LoadBalancer.

feat: allow setting annotations on mc-router services

---

charts/minecraft-proxy/Chart.yaml
charts/minecraft-proxy/templates/deployment.yaml
charts/minecraft-proxy/templates/secret.yaml

Fixed secret reference name in deployment, there's no "-rcon" appended in the secret's template.

Fix secret name for RCON password in proxy

---

charts/mc-router/Chart.yaml
charts/mc-router/templates/deployment.yaml
charts/mc-router/values.schema.json
charts/mc-router/values.yaml
charts/minecraft-bedrock/Chart.yaml
charts/minecraft-bedrock/templates/deployment.yaml
charts/minecraft-bedrock/values.yaml
charts/minecraft-proxy/Chart.yaml
charts/minecraft-proxy/templates/deployment.yaml
charts/minecraft-proxy/values.yaml
charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/values.schema.json
charts/minecraft/values.yaml

Not sure how this is normally tested, so here are examples of the template output.
Fixes #204.
```
$ helm template  charts/minecraft  --set 'minecraftServer.eula=true' --set 'extraPodSpec.priorityClassName=test-priority-class' | grep 'test-priority-class' -C 10
drop:
- ALL
readOnlyRootFilesystem: true
volumes:
- name: tmp
emptyDir: {}
- name: datadir
emptyDir: {}
- name: backupdir
emptyDir: {}
priorityClassName: test-priority-class
```
```
$ helm template  charts/minecraft-bedrock  --set 'minecraftServer.eula=true' --set 'extraPodSpec.priorityClassName=test-priority-class' | grep 'test-priority-class' -C 10
allowPrivilegeEscalation: false
capabilities:
drop:
- ALL
readOnlyRootFilesystem: true
volumes:
- name: tmp
emptyDir: {}
- name: datadir
emptyDir: {}
priorityClassName: …
```

Add extraPodSpec to allow customizing Pods

---

charts/minecraft/values.yaml

The NFS volume extraVolumes example in charts/minecraft/values.yaml is missing the "nfs" key needed to define a proper NFS typed volume. Without it, the helm chart templates render an emptyDir volume instead and complain about unknown values. Adding that key renders a working NFS volume in the pod definition.
```
$ helm install my-minecraft minecraft-server-charts/minecraft --set minecraftServer.eula=true,persistence.dataDir.enabled=true --set "extraVolumes[0].volumeMounts[0].name=nfs,extraVolumes[0].volumeMounts[0].mountPath=/mnt/volume,extraVolumes[0].volumeMounts[0].readOnly=true,extraVolumes[0].volumes[0].name=nfs,extraVolumes[0].volumes[0].server=nas,extraVolumes[0].volumes[0].path=/mnt/minecraft"
W0513 22:19:06.143355   31321 warnings.go:70] unknown field …
```

Update NFS extraVolumes example in values.yaml

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/NOTES.txt
charts/minecraft/templates/deployment.yaml
charts/minecraft/values.yaml

I have an NFS share that contains the contents of my Minecraft server and would like to use it as the volume that gets mounted to `/data` directory in the container. As far as I can tell, it is not possible to configure the Minecraft Helm chart in this manner because an `emptyDir` volume is always mounted when the PVC is disabled and thus a conflict occurs.
To allow any defined extra volume to be mounted to the /data directory, I propose a new `extraDataVolume` configuration be introduced.
Thanks in advance for taking a look.
Example use with NFS:
```
persistence:
extraDataVolume: nfs
extraVolumes:
volumes:
- name: nfs
nfs:
server: example.nfs.server
path: /data/minecraft
```

Allow configuration to mount extra volume to /data

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml

Since Kubernetes will make Secrets volume to be mounted as read-only, when mc-backup is trying to run `mkdir` in [this line](https://github.com/itzg/docker-mc-backup/blob/aea603f867e3aab2bb0165d7db93d595c6966ccb/scripts/opt/backup-loop.sh#L305), our pod will show the following error:
```
2024-06-22T00:59:20+0800 INFO sleeping 24h...
2024/06/22 00:59:24 ERROR : Failed to save config after 10 tries: failed to create temp file for new config: open /config/rclone/rclone.conf59648627: read-only file system
```
To fix this issue, we can create a new empty volume and use InitContainer to copy the content of the Secrets volume to the new volume. Then we can mount the new volume as read-write in the main container.
I've tested this on my environment and now my `mc-backup` pod can successfully …

Fix: Make rclone config folder writable

---

charts/mc-router/Chart.yaml
charts/mc-router/templates/router-service.yaml
charts/mc-router/values.yaml

This pull request adds the `extraServiceSpec` field inside the `service` object in the values.yaml
Allows for more flexibility on the user end
Closes #215

mc-router: Add extraServiceSpec for customizing services

---

charts/mc-router/Chart.yaml
charts/mc-router/templates/router-service.yaml

Closes #217 
Tested locally with the following values
```
services:
extraServiceSpec:
ipFamilies:
- IPv4
- IPv6
ipFamilyPolicy: PreferDualStack
```
```
> helm install -f values.yaml minecraft-server-charts-master/charts/mc-router/ --generate-name
creating 5 resource(s)
NAME: mc-router-1722869570
LAST DEPLOYED: Mon Aug  5 14:52:50 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```
Output
Additional testing can be done before merge if deemed required

Fix: mc-router extraServiceSpec wrong indentation

---

charts/minecraft-proxy/Chart.yaml
charts/minecraft-proxy/templates/deployment.yaml
charts/minecraft-proxy/values.yaml

I noticed that there's no way to set the number of replicas for the proxy deployment - just added the bare minimum, but can make additions as needed

Add replicaCount configuration to minecraft-proxy chart

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/extraports-ing.yaml

Removes the requirement of setting `ingress.enabled: false` for extraPorts. For example, an item in `extraPorts[]` needing no ingress currently requires:
```yaml
extraPorts:
- name: map
protocol: TCP
ingress:
enabled: false
...
```
If `ingress` is omitted, the following error is thrown:
```text
Error: template: minecraft-toiletbowl/charts/minecraft/templates/extraports-ing.yaml:3:26: executing "minecraft-toiletbowl/charts/minecraft/templates/extraports-ing.yaml" at <.ingress.enabled>: nil pointer evaluating interface {}.enabled
```
With this update, we can safely omit the `ingress` object entirely:
```yaml
extraPorts:
- name: map
protocol: TCP
...
```

Allow optional definition of ingress

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml

Updates the arrangement containers to ensure the minecraft server is always used for `exec` and `log`
Resolves #223

Reorder minecraft chart containers 

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/minecraft-svc.yaml
charts/minecraft/templates/rcon-svc.yaml
charts/minecraft/values.yaml

For services `spec.loadBalancerClass` allows you to specify a LoadBalancer implementation other than the cloud provider default:
https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class
This PR adds the ability to specify the loadBalancerClass for the Minecraft and RCON services.

Allow setting loadBalancerClass

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/_helpers.tpl
charts/minecraft/templates/deployment.yaml
charts/minecraft/templates/extra-list.yaml
charts/minecraft/values.schema.json
charts/minecraft/values.yaml

Adds the ability for users to use templating within the `initContainers` and `sidecarContainers` values.
Summary of changes:
* renames existing `extraDeploy.render` helper function to `tplRender`
* removes multiple `initContainers` keys in deployment when `initContainers` is specified with rclone backups
* uses `tplRender` function to process `initContainers` and `sidecarContainers`
* add templating examples to `values.yaml`
* add `initContainers`, `sidecarContainers` and `extraDeploy` to values schema

Add templating to initContainers and sidecarContainers

---

charts/minecraft-bedrock/Chart.yaml
charts/minecraft-bedrock/values.yaml
charts/minecraft/Chart.yaml
charts/minecraft/values.yaml

Since the default tag is "latest" and features arrive fairly frequently, it's more intuitive to have the latest image be more aggressive about checking for updates in the registry. The download itself is skipped if the latest image is already on the node, so it's a minor network penalty at pod creation time.

Default image pull policy to Always

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/values.yaml

Option to disable TTY for Minecraft Java servers, as described [here](https://docker-minecraft-server.readthedocs.io/en/latest/configuration/misc-options/#interactive-and-color-console).

Add option to disable TTY

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/_helpers.tpl
charts/minecraft/values.schema.json
charts/minecraft/values.yaml

Resolves #245
Fixes regression from #241

minecraft: restore default value handling

---

.github/workflows/lint-test.yaml
charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/values.yaml

Add direct support for fabric settings

minecraft: fabric support

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/values.schema.json
charts/minecraft/values.yaml

Once again, thank you so much for this project!
Right now, when trying to download Modrinth plugins, there's no support for [MODRINTH_DOWNLOAD_DEPENDENCIES](https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/modrinth/#extra-options). This means that there is no way to specify to download required dependencies from Modrinth and they all must be manually specified. This PR fixes that
(Note - this is my first time modifying a helm chart, so you should probably make sure there's nothing else I missed changing. This should still provide backwards compatibility, but I don't know if you would also want to bump the version number)

Add support for MODRINTH_DOWNLOAD_DEPENDENCIES

---

charts/minecraft/Chart.yaml
charts/minecraft/templates/_helpers.tpl
charts/minecraft/values.yaml

Adds `nameOverride` and `fullnameOverride` to the chart/helpers, as per the [mc-router chart](https://github.com/itzg/minecraft-server-charts/blob/80e95abdf88492d5c1dee13860c10a704c14bcae/charts/mc-router/templates/_helpers.tpl#L13-L24).
Closes #252

feat: add nameOverride and fullnameOverride to minecraft chart

---

charts/minecraft-bedrock/Chart.yaml
charts/minecraft-bedrock/templates/_helpers.tpl
charts/minecraft-bedrock/templates/datadir-pvc.yaml
charts/minecraft-bedrock/templates/deployment.yaml
charts/minecraft-bedrock/templates/minecraft-svc.yaml
charts/minecraft-proxy/Chart.yaml
charts/minecraft-proxy/templates/_helpers.tpl
charts/minecraft-proxy/templates/configmap.yaml
charts/minecraft-proxy/templates/datadir-pvc.yaml
charts/minecraft-proxy/templates/deployment.yaml
charts/minecraft-proxy/templates/proxy-svc.yaml
charts/minecraft-proxy/templates/rcon-secret.yaml
charts/minecraft-proxy/templates/rcon-svc.yaml
charts/minecraft-proxy/templates/velocity-forwarding-secret.yaml
charts/minecraft/Chart.yaml
charts/minecraft/templates/_helpers.tpl
charts/minecraft/templates/backupdir-pvc.yaml
charts/minecraft/templates/datadir-pvc.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/templates/minecraft-svc.yaml
charts/minecraft/templates/rclone-secret.yaml
charts/minecraft/templates/rcon-svc.yaml
charts/minecraft/templates/secrets.yaml

This is a prerequisite for #254
```
failed to create resource: Secret "minecraft-<name>-rcon" is invalid: [metadata.labels: Invalid value: "minecraft-4.25.0+efa491f67fbd": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), metadata.labels: Invalid value: "4.25.0+efa491f67fbd": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]
```

Fix charts.version for OCI chart rendering

---

.github/workflows/lint-test.yaml
.github/workflows/release.yaml
charts/minecraft-proxy/Chart.yaml
charts/minecraft-proxy/templates/extraports-ing.yaml
charts/minecraft-proxy/templates/extraports-svc.yaml
charts/minecraft/Chart.yaml
charts/minecraft/templates/_helpers.tpl
charts/minecraft/templates/backupdir-pvc.yaml
charts/minecraft/templates/datadir-pvc.yaml
charts/minecraft/templates/deployment.yaml
charts/minecraft/templates/extraports-ing.yaml
charts/minecraft/templates/extraports-svc.yaml
charts/minecraft/templates/minecraft-svc.yaml
charts/minecraft/templates/rclone-secret.yaml
charts/minecraft/templates/rcon-svc.yaml
charts/minecraft/templates/secrets.yaml

Update the release pipeline to continue to push to the ghcr helm repository, as well as push an OCI image and sign it.
This also cleans up the chart.version reference using a template.
This publishes the objects as `ghcr.io/itzg/minecraft-server-charts/<chartname>`
Successful run: https://github.com/joryirving/minecraft-server-charts/actions/runs/13891040259/job/38862979875
OCI artifact for mc-router: https://github.com/joryirving/minecraft-server-charts/pkgs/container/minecraft-server-charts%2Fmc-router
OCI artifact for minecraft: https://github.com/joryirving/minecraft-server-charts/pkgs/container/minecraft-server-charts%2Fminecraft
I've tested it successfully in my own cluster, and the changes to chart-version work.
Unfortunately, I couldn't get cosign working: …

OCI chart release

---

charts/mc-router/Chart.yaml
charts/mc-router/templates/autoscale-allow-deny-configmap.yaml
charts/mc-router/templates/autoscale-allow-deny-secret.yaml
charts/mc-router/templates/clusterrole.yaml
charts/mc-router/templates/deployment.yaml
charts/mc-router/templates/secret.yaml
charts/mc-router/values.schema.json
charts/mc-router/values.yaml

Update mc-router chart for new auto scale options
