- README.md
To make the rendered https://itzg.github.io/minecraft-server-charts/ page have some detail.
> add some detail to the gh-pages README

- charts/minecraft-bedrock/.helmignore
- charts/minecraft-bedrock/Chart.yaml
- charts/minecraft-bedrock/OWNERS
- charts/minecraft-bedrock/README.md
- charts/minecraft-bedrock/ci/test-values.yaml
- charts/minecraft-bedrock/templates/NOTES.txt
- charts/minecraft-bedrock/templates/_helpers.tpl
- charts/minecraft-bedrock/templates/datadir-pvc.yaml
- charts/minecraft-bedrock/templates/deployment.yaml
- charts/minecraft-bedrock/templates/minecraft-svc.yaml
- charts/minecraft-bedrock/values.yaml
Adding bedrock Chart
There are a few things that should probably get updated. I believe there might be conflicts if you ran the minecraft and minecraft-bedrock charts in the same namespace.
> Init bedrock chart

- charts/minecraft/Chart.yaml
- charts/minecraft/templates/datadir-pvc.yaml
Reverts itzg/minecraft-server-charts#9
> [minecraft] - Revert #9

- charts/minecraft-bedrock/Chart.yaml
- charts/minecraft-bedrock/templates/datadir-pvc.yaml
- charts/minecraft-bedrock/values.yaml
Reverts itzg/minecraft-server-charts#10
> [minecraft-bedrock] - Revert #10

- charts/minecraft-bedrock/Chart.yaml
- charts/minecraft-bedrock/templates/deployment.yaml
- charts/minecraft-bedrock/values.yaml
This requires the docker changes in https://github.com/itzg/docker-minecraft-bedrock-server/pull/102 to work properly.
> Adding permissions to bedrock chart

- .github/workflows/release.yaml
This is related to https://helm.sh/blog/new-location-stable-incubator-charts/
Fixes #24
> fix helm stable repo

- charts/minecraft/Chart.yaml
- charts/minecraft/templates/deployment.yaml
> Fix ENABLE_RCON for minecraftServer.rcon.enable false

- charts/minecraft-bedrock/Chart.yaml
- charts/minecraft-bedrock/templates/deployment.yaml
- charts/minecraft-bedrock/values.yaml
- charts/minecraft/Chart.yaml
- charts/minecraft/templates/deployment.yaml
- charts/minecraft/values.yaml
> feature(java, bedrock): added init containers & extra volumes

- README.md
Add `repo` in `helm search` command.
> fix helm command

- charts/minecraft/Chart.yaml
- charts/minecraft/templates/deployment.yaml
Should be self-explanatory, fixes #35
> fix(minecraft): quote query port values (fixes #35)

- charts/bungee/.helmignore
- charts/bungee/Chart.yaml
- charts/bungee/README.md
- charts/bungee/templates/NOTES.txt
- charts/bungee/templates/_helpers.tpl
- charts/bungee/templates/bungee-svc.yaml
- charts/bungee/templates/configmap.yaml
- charts/bungee/templates/datadir-pvc.yaml
- charts/bungee/templates/deployment.yaml
- charts/bungee/templates/rcon-svc.yaml
- charts/bungee/templates/secret.yaml
- charts/bungee/values.yaml
I've attempted to follow the standards of the other charts in this repo as closely as possible, I'm sure this needs to be iterated on
Let me know if anything should be changed, this is open to edits
> feat: add chart for bungeecord

- charts/minecraft/Chart.yaml
- charts/minecraft/templates/datadir-pvc.yaml
- charts/minecraft/templates/dynmap-ing.yaml
- charts/minecraft/templates/dynmap-svc.yaml
- charts/minecraft/values.yaml
Adds PVC annotations
Edit: I just caught that the new extraPort service violates RFC 1123, as it must always be lowercase. Fixed it as well
> Pvc annotations, fixed extraPort service

- .github/workflows/lint-test.yaml
- charts/minecraft/Chart.yaml
- charts/minecraft/templates/_helpers.tpl
- charts/minecraft/templates/extraports-ing.yaml
Let's not discriminate those with older k8s versions :)
I'll rebase this once #59 hits master
> set ingress apiversion in accordance to k8s version

- charts/minecraft/Chart.yaml
- charts/minecraft/templates/deployment.yaml
- charts/minecraft/values.yaml
Hello! This PR adds spawn-protection value to be editable on Helm chart.
The original feature is based on https://github.com/itzg/docker-minecraft-server/#set-spawn-protection
> Add spawn protection in helm chart value

- charts/minecraft/Chart.yaml
- charts/minecraft/templates/deployment.yaml
- charts/minecraft/values.yaml
https://github.com/itzg/minecraft-server-charts/pull/96
Changed the branch in my repo and that didnt go as planned…
>  Allow adding sidecarContainers

- charts/minecraft/Chart.yaml
- charts/minecraft/templates/deployment.yaml
- charts/minecraft/values.yaml
In by its own there will probably be not that many people that have a usecase for this, i dont think it hurts to have it configurable though, keeps me from making a hard fork of this chart for now :P
> Allow setting deployment replica count

- charts/minecraft/Chart.yaml
- charts/minecraft/templates/deployment.yaml
- charts/minecraft/values.yaml
Add the `OVERRIDE_SERVER_PROPERTIES` ENV to the deployment
fixes #92
> Add Override Server Properties ENV

- charts/minecraft/Chart.yaml
- charts/minecraft/templates/deployment.yaml
- charts/minecraft/templates/rclone-secret.yaml
- charts/minecraft/values.yaml
Switch rclone.config `configmap` to a secret, also add `rcloneConfigExistingSecret` as an option as requested.
fixes #100
> Update RClone Config

- charts/minecraft/Chart.yaml
- charts/minecraft/templates/deployment.yaml
> Mapped PRUNE_BACKUPS_DAYS into backup container

- charts/minecraft/Chart.yaml
- charts/minecraft/templates/deployment.yaml
check if is volumes before writing
#112
> extravolumes: extraVolumes - check if element is a volume before writing

- charts/minecraft-proxy/Chart.yaml
- charts/minecraft-proxy/templates/deployment.yaml
- charts/minecraft-proxy/values.yaml
> feat(minecraft-proxy): added valueFrom support

- charts/minecraft/Chart.yaml
- charts/minecraft/templates/deployment.yaml
- charts/minecraft/values.yaml
- Fix template error when only passing a single Spigot Resource
- Add chart support for Vanilla Tweaks
- Add chart support for server resource pack
> Support Resource Packs

- charts/minecraft/Chart.yaml
- charts/minecraft/templates/deployment.yaml
- charts/minecraft/values.yaml
> minecraft: change probes to use mc-health

- charts/minecraft-proxy/Chart.yaml
- charts/minecraft-proxy/templates/deployment.yaml
- charts/minecraft-proxy/values.yaml
> feat(minecraft-proxy): add sidecar container support

- charts/minecraft/Chart.yaml
- charts/minecraft/templates/deployment.yaml
- charts/minecraft/values.yaml
This allow configuring probe commands in values.yaml
> Make probe commands configurable

- charts/minecraft-bedrock/Chart.yaml
- charts/minecraft-bedrock/templates/minecraft-svc.yaml
This should fix annotation parsing on the service, so that multiple annotations can be specified
> Fix annotations parsing

- charts/minecraft/Chart.yaml
- charts/minecraft/templates/deployment.yaml
This will allow users to access and interact with their console using `kubectl attach` 
Example in our chart repo: https://github.com/mcserverhosting-net/charts/blob/master/chart/forge-deployment/templates/server-statefulset.yaml#L57-L58
> Enable tty/stdin

- charts/minecraft/Chart.yaml
- charts/minecraft/templates/deployment.yaml
- charts/minecraft/templates/minecraft-svc.yaml
- charts/minecraft/templates/rcon-svc.yaml
- charts/minecraft/values.schema.json
- charts/minecraft/values.yaml
Originally I wanted to just add labels, but then I went a bit overboard and added everything that I had to define through extra env vars for my own servers. Also added a schema file that will verify if values are valid, I'll leave it to your judgment to decide if that's something that you want.
> Extra labels, Modrinth, CurseForge and regural URLs

- charts/minecraft/Chart.yaml
- charts/minecraft/templates/deployment.yaml
- charts/minecraft/templates/secrets.yaml
- charts/minecraft/values.schema.json
- charts/minecraft/values.yaml
Fixes this error: `wrong number of args for join: want 2 got 0`
> fix: Add parentheses for joins, add CurseForge API key

- charts/minecraft/Chart.yaml
- charts/minecraft/templates/deployment.yaml
- charts/minecraft/values.schema.json
Seems like my brain doesn't want to work on weekend, sorry for spam. Missed join function in few places, missed modUrls during merge conflict resolve. I've tested with `helm template .`, all new values look correct, hope this is last PR for this change =)
> fix: Actually join lists where needed

- charts/minecraft-bedrock/Chart.yaml
- charts/minecraft-bedrock/templates/datadir-pvc.yaml
- charts/minecraft-bedrock/values.yaml
- charts/minecraft/Chart.yaml
- charts/minecraft/templates/datadir-pvc.yaml
- charts/minecraft/values.yaml
Adds PVC labels
Similar PR: #58
> Pvc labels

- charts/minecraft-proxy/Chart.yaml
- charts/minecraft-proxy/templates/deployment.yaml
> proxy: enable tty and stdin

- charts/minecraft-bedrock/Chart.yaml
- charts/minecraft-bedrock/templates/deployment.yaml
- charts/minecraft-bedrock/templates/minecraft-svc.yaml
- charts/minecraft-bedrock/values.yaml
I need this for k3s serviiceLB, IMO it should be annotations but that is a different story. ;)
https://docs.k3s.io/networking/networking-services#creating-servicelb-node-pools
Thank you for your hard work!
> add customisable deployment and service lables

- charts/minecraft/Chart.yaml
- charts/minecraft/values.yaml
> updated doc in Server Type to AUTO_CURSEFORGE

- charts/mc-router/Chart.yaml
- charts/mc-router/templates/_helpers.tpl
- charts/mc-router/templates/deployment.yaml
- charts/minecraft/Chart.yaml
- charts/minecraft/templates/_helpers.tpl
- charts/minecraft/templates/deployment.yaml
See Issue #227 
Also resorb mc-router envBoolMap, can revert this if not wanted.
> Fix: Spawn protection setting bugged 

- charts/mc-router/Chart.yaml
- charts/minecraft-bedrock/Chart.yaml
> Bump chart version for OCI chart release 

- charts/minecraft/Chart.yaml
- charts/minecraft/templates/extraports-ing.yaml
this fixes the error caused by enabling ingress on an extraPort mentioned in #262
> fix: extraports ingress template context

- charts/minecraft/Chart.yaml
- charts/minecraft/templates/deployment.yaml
- charts/minecraft/values.yaml
Hey, just adding a little value to the yaml for the revisionHistoryLimit setting for Deployments.
> Add revisionHistoryLimit to Minecraft values
